### ISSUE TITLE
wiki更新エラー

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/seiyu_watch#81]
カテゴリのところかなぁ？
```
16:12:15.304 [error] Task #PID<0.6518.0> started from #PID<0.6517.0> terminating
** (FunctionClauseError) no function clause matching in SeiyuWatch.WikipediaResponse.categories/1
    (seiyu_watch) lib/tasks/wikipedia_response.ex:68: SeiyuWatch.WikipediaResponse.categories(%{"canonicalurl" => "https://ja.wikipedia.org/wiki/%E5%92%8C%E6%B0%A3%E3%81%82%E3%81%9A%E3%81%BF", "contentmodel" => "wikitext", "editurl" => "https://ja.wikipedia.org/w/index.php?title=%E5%92%8C%E6%B0%A3%E3%81%82%E3%81%9A%E3%81%BF&action=edit", "fullurl" => "https://ja.wikipedia.org/wiki/%E5%92%8C%E6%B0%A3%E3%81%82%E3%81%9A%E3%81%BF", "missing" => "", "ns" => 0, "pagelanguage" => "ja", "pagelanguagedir" => "ltr", "pagelanguagehtmlcode" => "ja", "title" => "和氣あずみ"})
    (seiyu_watch) lib/tasks/seiyu_parser.ex:10: SeiyuWatch.SeiyuParser.save/1
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by ganta** [comment]
×`和氣あずみ` => ○`和氣あず未`

**Comment by h3poteto** [comment]
(｡◉ᆺ◉)

**Comment by h3poteto** [comment]
```
16:42:09.859 [error] Task #PID<0.2012.0> started from #PID<0.2011.0> terminating
** (FunctionClauseError) no function clause matching in SeiyuWatch.WikipediaResponse.categories/1
    (seiyu_watch) lib/tasks/wikipedia_response.ex:68: SeiyuWatch.WikipediaResponse.categories(%{"canonicalurl" => "https://ja.wikipedia.org/wiki/%E7%A8%AE%EF%A8%91%E6%95%A6%E7%BE%8E", "contentmodel" => "wikitext", "editurl" => "https://ja.wikipedia.org/w/index.php?title=%E7%A8%AE%EF%A8%91%E6%95%A6%E7%BE%8E&action=edit", "fullurl" => "https://ja.wikipedia.org/wiki/%E7%A8%AE%EF%A8%91%E6%95%A6%E7%BE%8E", "lastrevid" => 48971802, "length" => 24, "new" => "", "ns" => 0, "pageid" => 2840320, "pagelanguage" => "ja", "pagelanguagedir" => "ltr", "pagelanguagehtmlcode" => "ja", "redirect" => "", "revisions" => [%{"parentid" => 0, "revid" => 48971802, "sha1" => "b9a3cf81c1f29f6daa1db3dfb3826e0e3d3c3fe8"}], "title" => "種﨑敦美", "touched" => "2016-11-21T12:19:45Z"})
    (seiyu_watch) lib/tasks/seiyu_parser.ex:10: SeiyuWatch.SeiyuParser.save/1
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
これも

**Comment by h3poteto** [comment]
いずれも登録の部分だな
